name: Run_Python_test
on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: '0'
        - name: git
          run: |
            
            git diff --name-only HEAD HEAD~1
            env:
              MOD_FILES: ${{ git diff --name-only HEAD HEAD~1 }}

        - name: slack push
          uses: pullreminders/slack-action@master
          if: contains(github.event.head_commit.message, 'kp')
      
          env:
              SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
              
          with:
            args: '{\"channel\":\"C03LV8M6P25\",\"text\":\" Following files have been changed by ${{github.event.commits[0].author.username}}: \n ${{env.MOD_FILES}}  \"}'  

 
  job2:
    needs: job1
  # The type of runner that the job will run on
    runs-on: ubuntu-latest

  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Notify slack changeCompare
      if: contains(github.event.head_commit.message, 'kp')
      
      env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          
          
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"C03LV8M6P25\",\"text\":\" See the documentation changes done by ${{github.event.commits[0].author.username}} by following the link below:\n ${{github.event.compare}} \"}'  
