name: Run_Python_test
on:
  push:
    branches: [main]
 

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |

            path = 'https://docs.cognite.com/'
            import re
            message = str("""${{github.event.head_commit.message}}""").replace("\n\n", "##").replace("\n", "@")
            reg_result = re.search('##(.*)', message)
            
            commit_description = reg_result.group(1)
            description_arr = commit_description.split("@")
            print("description_arr"+description_arr)

            for file_url in description_arr:
              print("file_url"+file_url)
              search_text  = ".md"      
              reg_match = re.search('docs(.*).md', file_url)  
              print("reg_match"+reg_match)    
                          

              if search_text in str(file_url):
                print("Search term:'"+search_text+"' found in "+file_url)
              else:
                print("Search term:'"+search_text+"' NOT found in "+file_url)



  build2:
  # The type of runner that the job will run on
    runs-on: ubuntu-latest

  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Notify slack
      if: contains(github.event.head_commit.message, 'kp')
      
      env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          
          
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"C03LV8M6P25\",\"text\":\"Changes were commited to main by ${{github.event.commits[0].author.username}}  ${{github.event.compare}}\"}'  
        
