name: Run_Python_test
on:
  push:
    branches: [main]
 

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            
            import urllib.request
            with urllib.request.urlopen('https://w3schools.com/python/demopage.htm') as response:
              html = response.read()
            
            print(str('${{github.event.commits[0].author.username}}'))
            print("Directory contents:")
            for f in os.listdir():
                print(f)


  build2:
  # The type of runner that the job will run on
    runs-on: ubuntu-latest

  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Notify slack
      if: contains(github.event.head_commit.message, 'wathsya')
      
      env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          
          
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"C03LV8M6P25\",\"text\":\"Wathsya Changes were commited to main by ${{github.event.commits[0].author.username}}  ${{github.event.repository.contents_url}}\"}'  
        
