name: Run_Python_test
on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest 
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: '0'
        - name: git
          run: |
            # I use 'GitHub Actions Bot' with no email by default
            firstString=$(git diff --name-only HEAD HEAD~1)
            echo $firstString
            search="src/docs"
            replace="https://docs.cognite.com"
            secondString="${firstString//"$search"/"$replace"}" 
            search2=".md"
            replace2=" \n"
            thirdString="${secondString//"$search2"/"$replace2"}"
            echo $thirdString
            search3="index"
            replace3=" "
            finalString="${thirdString//"$search3"/"$replace3"}"
            
            
            finalString=$(tr -dc '[[:print:]]' <<< "$finalString")
            echo "MOD_FILES=$finalString" >> $GITHUB_ENV
        - name: pushslack
          uses: pullreminders/slack-action@master
          if: contains(github.event.head_commit.message, 'kp')
      
          env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
                
          with:
            args: '{\"channel\":\"C03LV8M6P25\",\"text\":\" Following documents have been changed: \n ${{env.MOD_FILES}}  \"}' 
                    
