name: Run_Python_test
on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
      
        with:
          script: |

            path = 'https://docs.cognite.com/'
            import re
            message = str("""${{github.event.head_commit.message}}""").replace("\n\n", "##").replace("\n", "@")
            reg_result = re.search('##(.*)', message)
            
            commit_description = reg_result.group(1)
            description_arr = commit_description.split("@")
            print(description_arr)

            for file_url in description_arr:
              print("file_url"+file_url)
              search_text  = ".md"      
              reg_match = str(re.search('docs(.*).md', file_url).group(1))  
              
              if reg_match != "": 
                generated_path = path+reg_match
                print("reg_match:"+generated_path)
                set_env("path1", generated_path)

      - uses: pullreminders/slack-action@master
        if: contains(github.event.head_commit.message, 'kp')
      
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          Greeting: Hello
          
                    
        with:
          args: '{\"channel\":\"C03LV8M6P25\",\"blocks\":\"[{"type": "section", "text": {"type": "plain_text", "text": "Hello world"}}]\"}'  
          #args: '{\"channel\":\"C03LV8M6P25\",\"text\":\"${{github.event.compare}} Changes were commited to main by ${{github.event.commits[0].author.username}}  ${{github.event.compare}}\"}'  
   
 
